[
	{
		"id":"64",
		"name":"DisplayTime.java",
		"path":"/Users/zhaoziqi/Documents/Study/JAVA/IntelliJProject/ExUpload/target/classes/webapp/upload/DisplayTime.java",
		"size":"1.34KB",
		"type":"application/octet-stream",
		"update":"2018-07-30 04:56:14.0"
	},
	{
		"id":"68",
		"name":"snake.code-workspace",
		"path":"/Users/zhaoziqi/Documents/Study/JAVA/IntelliJProject/ExUpload/target/classes/webapp/upload/snake.code-workspace",
		"size":"51B",
		"type":"application/octet-stream",
		"update":"2018-07-30 10:57:47.0"
	},
	{
		"id":"70",
		"name":"VMware Fusion_10.1.2-8502123_xclient.info.dmg",
		"path":"/Users/zhaoziqi/Documents/Study/JAVA/IntelliJProject/ExUpload/upload/VMware Fusion_10.1.2-8502123_xclient.info.dmg",
		"size":"434.13MB",
		"type":"application/octet-stream",
		"update":"2018-07-31 09:42:20.0"
	},
	{
		"id":"71",
		"name":"CentOS-7-x86_64-DVD-1804.iso",
		"path":"/Users/zhaoziqi/Documents/Study/JAVA/IntelliJProject/ExUpload/upload/CentOS-7-x86_64-DVD-1804.iso",
		"size":"4.17GB",
		"type":"application/octet-stream",
		"update":"2018-07-31 10:47:27.0"
	},
	{
		"id":"73",
		"name":"day04-JavaScript.torrent",
		"path":"/Users/zhaoziqi/Documents/Study/JAVA/IntelliJProject/ExUpload/upload/day04-JavaScript.torrent",
		"size":"24.37KB",
		"type":"application/x-bittorrent",
		"update":"2018-07-31 02:46:15.0"
	}
]